### ISSUE TITLE
What does it mean 'locked'?

### ISSUE THREAD

**Issue by berkas1** [bigclownlabs/doc.bigclown.com#12]
Hi, README says 'locked' - does that mean that no commits (pull requests) (like new sample projects) will be accepted?

**Comment by hubpav** [comment]
Hi Simon, it means we have new repo we are working on where we have website+blog+documentation united. We very much appreciate your contribution! Thx in advance. The new repo is this: https://github.com/bigclownlabs/bc-website ... We deploy the working version on commit to master here: http://bigclown.netlify.com/en/ ... Shoot me an email, please, I will be happy to have a quick conf call about the structure if you dont mind. Cheers! P.

**Comment by berkas1** [comment]
Thanks Pavel, mail is berka 'at' berkasimon.com. We can use google hangouts there directly, otherwise Telegram or good old phone call :D
